### ISSUE TITLE
`author` field as string is not validated

### ISSUE THREAD

**Issue by piranna** [keindev/package-json-helper#453]
Using a string instead of an object throws a `Person name is required` error, while using a string is a valid option.

**Comment by keindev** [comment]
> Using a string instead of an object throws a `Person name is required` error, while using a string is a valid option.

[npm docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#people-fields-author-contributors) states that: `A "person" is an object with a "name" field and optionally "url" and "email"`

Can you give an example that causes an error and does not contradict the documentation?

**Comment by piranna** [comment]
> Can you give an example that causes an error and does not contradict the documentation?

Just in the next paragraph of the documentation:

> Or you can shorten that all into a single string, and npm will parse it for you:
>
> ```json
> {
>   "author": "Barney Rubble <b@rubble.com> (http://barnyrubble.tumblr.com/)"
> }
> ```
>
> Both email and url are optional either way.
>
> npm also sets a top-level "maintainers" field with your npm user info.

**Comment by piranna** [comment]
`npm` would normalize it, but since we are reading the `package.json` file ourselves, we need to do the normalization by our own.

**Comment by keindev** [comment]
> `npm` would normalize it, but since we are reading the `package.json` file ourselves, we need to do the normalization by our own.

In tests, I check normalized strings and parse them into objects ([link](https://github.com/keindev/package-json-helper/blob/main/src/__tests__/Package.test.ts#L111))

Sorry, I do not quite understand at what point the exception - `Person name is required` occurs.

`Barney Rubble <b@rubble.com> (http://barnyrubble.tumblr.com/)` is valid Person string and it's convert to Object correctly.

**Comment by piranna** [comment]
Check it without the email, only the url (or viceversa), and it should fail the validation.

**Comment by piranna** [comment]
Thank you :-)
